#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Searching tests makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

PROG = searching-tests
SRCS = searching-tests.cpp
LFLAGS += -L${ROOT_DIR}/lib/Searching
LIBS += -lsearching

include $(abspath ../makefile-test.common)
