#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Test-level makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

default:
	$(MAKE) -C sorting
	$(MAKE) -C searching
	$(MAKE) -C data-structures

clean:
	$(MAKE) -C sorting clean
	$(MAKE) -C searching clean
	$(MAKE) -C data-structures clean
