#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Test-level makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

all:
	$(MAKE) -C sorting
#	$(MAKE) -C searching
#	$(MAKE) -C data_structures

.PHONY: clean

clean:
	$(MAKE) -C sorting clean
#	$(MAKE) -C searching clean
#	$(MAKE) -C data_structures clean
