#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Searching library makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

SRC = SearchUtil.cpp
LIB = libsearching.a

include $(abspath ../makefile-lib.common)
