#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief String Utility library makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

SRC = StringUtil.cpp
LIB = libstringUtil.a

include $(abspath ../makefile-lib.common)
