#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Sorting library makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

SRC = Sorting.cpp
LIB = libsorting.a

include $(abspath ../makefile-lib.common)
