#############################
##
##  File:
##      makefile
##
##  Description:
##      Sorting library makefile for C++ Libraries
##
##  Author:
##      J. Caleb Wherry
##
#############################

SRC = Sorting.cpp
LIB = libsorting.a

#include $(realpath ../makefile-lib.common)
include /home/calebwherry/Downloads/repos_github/Cpp-Libraries/lib/makefile-lib.common
