#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Sorting tests makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

PROG = sorting_tests
SRCS = tests.cpp
LFLAGS += -L${ROOT_DIR}/lib/Sorting
LIBS += -lsorting

include $(abspath ../makefile-test.common)
