#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Sorting tests makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

PROG = sorting-tests
SRCS = sorting-tests.cpp
LFLAGS += -L${ROOT_DIR}/lib/Sorting
LIBS +=

include $(abspath ../makefile-test.common)
