#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Library-level makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

all:
	$(MAKE) -C Searching
	$(MAKE) -C StringUtil
#	$(MAKE) -C Sorting	**TEMPLATED HEADERS**
#	$(MAKE) -C DataStructures   **TEMPLATED HEADERS**

.PHONY: clean

clean:
	$(MAKE) -C Searching clean
	$(MAKE) -C StringUtil clean
#	$(MAKE) -C Sorting clean	**TEMPLATED HEADERS**
#	$(MAKE) -C DataStructures clean **TEMPLATED HEADERS**
