#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief DX tests makefile
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

ROOT = $(abspath ../..)
PROG = data-structure-tests
SRCS = data-structure-tests.cpp
INCLUDES += -I${ROOT}/lib/DataStructures
LIBS +=

include $(abspath ../makefile-test.common)
