#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief DX tests makefile
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

PROG = data-structure-tests
SRCS = data-structure-tests.cpp
LFLAGS += -L${ROOT_DIR}/lib/DataStructures
LIBS +=

include $(abspath ../makefile-test.common)
