#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Sorting library makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

SRC = SinglyLinkedList.cpp DoublyLinkedList.cpp BinarySearchTree.cpp
LIB = libdatastructures.a

include $(abspath ../makefile-lib.common)
